/**
 * Generuje src/data/embedded-akpa-logos.ts z plików static/logos/akpa/.
 * Uruchom lokalnie: npm run logos:embed
 * Wygenerowany plik commituj – na produkcji (Railway) nie ma static/, więc logotypy są z tej mapy.
 */
import { readFileSync, readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const STATIC_DIR = join(process.cwd(), 'static', 'logos', 'akpa');
const OUT_FILE = join(process.cwd(), 'src', 'data', 'embedded-akpa-logos.ts');
const EXTS = ['.png', '.jpg', '.jpeg', '.gif', '.webp'];

function contentType(ext: string): string {
  if (ext === '.jpg' || ext === '.jpeg') return 'image/jpeg';
  if (ext === '.png') return 'image/png';
  if (ext === '.gif') return 'image/gif';
  return 'image/webp';
}

function main() {
  if (!existsSync(STATIC_DIR)) {
    console.error('Brak katalogu static/logos/akpa. Uruchom najpierw logos:export-db-to-static lub skopiuj pliki.');
    process.exit(1);
  }
  const entries: Array<{ id: string; contentType: string; base64: string }> = [];
  const files = readdirSync(STATIC_DIR);
  for (const file of files) {
    const match = file.match(/^(akpa_[a-zA-Z0-9_]+)(\.(png|jpg|jpeg|gif|webp))$/i);
    if (!match) continue;
    const id = match[1] ?? '';
    if (!id) continue;
    const ext = (match[3] ?? 'png').toLowerCase();
    const path = join(STATIC_DIR, file);
    const buf = readFileSync(path);
    const base64 = buf.toString('base64');
    entries.push({ id, contentType: contentType('.' + ext), base64 });
  }
  entries.sort((a, b) => a.id.localeCompare(b.id));
  const lines = [
    '// Auto-generated by npm run logos:embed – do not edit by hand.',
    '// Mapuje akpa_XXX -> { contentType, base64 } żeby logotypy działały bez plików na dysku (Railway).',
    '',
    'export const EMBEDDED_AKPA_LOGOS: Record<string, { contentType: string; base64: string }> = {',
    ...entries.map((e) => `  "${e.id}": { contentType: "${e.contentType}", base64: ${JSON.stringify(e.base64)} },`),
    '};',
    '',
    `export const EMBEDDED_AKPA_LOGOS_COUNT = ${entries.length};`,
  ];
  const outDir = join(process.cwd(), 'src', 'data');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`Zapisano ${entries.length} logotypów do ${OUT_FILE}`);
}

main();
